### ISSUE TITLE
CaretMessageHook() 增强

### ISSUE THREAD

**Issue by Frozen1084** [Tebayaki/AutoHotkeyScripts#1]
CaretMessageHook() 非常好用，简直是发现了宝藏一样。
我有几个explorer.exe相关的最常用的功能
1，用COM接口获取当前选择的文件和用ACC接口获取鼠标下的文件，但这个接口非常不稳定，性能也低，而且有时不可用，比如复制文件期间，接口会等待复制完成。
2，来自这个库 https://github.com/Ciantic/DisableFlashingTaskbarButtons
它修改explorer.exe内存，以禁止任务栏闪烁。

这两个功能很多人应该也会有需求，请问CaretMessageHook()能在注入后顺带兼容这两个功能吗？
如果能，那么explorer.exe相关的功能都像解锁了一样容易，比如现在获取explorer的当前路径，根据标签不准确，只能用COM接口，但COM接口也不稳定，最后只能发送复制，看看剪贴板内容。

**Comment by Tebayaki** [comment]
CaretMessageHook本意在于获取文本光标的坐标，我不打算添加其他功能。
这种修改内存的做法伴随着风险，我已经使用正式的接口实现了类似的功能，因此也不打算继续维护这个脚本，详见：https://github.com/Tebayaki/AutoHotkeyScripts/blob/main/lib/GetCaretPosEx.ahk

另外，关于第一点，我不清楚为什么你为什么会遇到不稳定的情况（我还没有遇到过），但com接口的本质其实就是往explorer.exe注入dll，这与使用机器码或者普通的dll注入手段实现的效果其实是类似的，因此我建议你检查代码是否有错误

**Comment by Frozen1084** [comment]
了解了，谢谢回复。
